search_lyrics:
  description: >
    Fetch song lyrics from Netease
  fields:
    entity_id:
      description: Entity ID to write lyrics to.
      example: sensor.foobar_lyrics
    media_artist:
      description: Name of the Artist
      example: Protoje
    media_title:
      description: Name of the Song.
      example: 'Mind of a King'
    media_position:
      description: Position of the Song player.
      example: 1
    media_state_time:
      description: Position update time.
      example: "2020-02-20T20:20:20.000000"
    media_lyrics:
      description: Lyrics of the song.
      example: ""
    media_lyrics_current:
      description: Current lyrics of the song.
      example: ""
